DROP TABLE TEST_VEHICLE1 IF EXISTS;

CREATE TABLE “TEST_VEHICLE1”
( “ID” NUMBER(19,0) NOT NULL ENABLE,
“VEHICLENUMBER” VARCHAR2(10 BYTE),
“BRAND” VARCHAR2(100 BYTE),
“COUNTRY” VARCHAR2(100 BYTE),
“MODELNAME” VARCHAR2(35 BYTE),
“MODELYEAR” VARCHAR2(35 BYTE),
PRIMARY KEY (“ID”)
) ;